# generated by datamodel-codegen:
#   filename:  boleta.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Tipo(Enum):
    mercado = 'mercado'
    limite = 'limite'
    stop = 'stop'
    stop_limite = 'stop_limite'
    mercado_por_faixa = 'mercado_por_faixa'


class Parcial(Enum):
    tudo_ou_nada = 'tudo_ou_nada'
    o_que_der = 'o_que_der'


class DestinoDoResto(Enum):
    agressivo = 'agressivo'
    cancelar = 'cancelar'


class BoletaUniversal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    lado: forma_schema.Lado
    tipo: Tipo = Field(
        ...,
        description='Tipo NEUTRO de ordem. Se o manifesto nao declarar esta capacidade, a boleta e recusada — nao adaptada.',
    )
    saldo_pct: forma_schema.DecimalPositivo = Field(
        ...,
        description='Percentagem do SALDO. E um valor do dono (RN-A1), nao uma constante do programa.',
    )
    alavancagem: forma_schema.DecimalPositivo = Field(
        ..., description='Multiplo de alavancagem pedido.'
    )
    stop_pct: forma_schema.DecimalPositivo | None = Field(
        None,
        description='Distancia de stop em percentagem de MOVIMENTO (nao em pontos). Ausente = este setup nao usa stop (RN-S3).',
    )
    tp_pct: forma_schema.DecimalPositivo | None = Field(
        None,
        description='Distancia de lucro em percentagem de MOVIMENTO. Ausente = sem alvo declarado.',
    )
    parcial: Parcial = Field(
        ...,
        description='Obrigatoria (RN-B6): o que fazer se so parte da quantidade couber. Escolha do setup, nunca do conector.',
    )
    desvio_maximo: forma_schema.DecimalPositivo = Field(
        ..., description='Desvio maximo de preco aceite, em percentagem de movimento.'
    )
    prazo_da_passiva_ms: forma_schema.DuracaoMs = Field(
        ...,
        description='Quanto tempo a parte passiva da ordem espera antes de o destino do resto decidir.',
    )
    destino_do_resto: DestinoDoResto = Field(
        ...,
        description='O que fazer com o que ficou por executar quando o prazo da passiva acaba.',
    )
    reduce_only: bool = Field(
        ...,
        description='So reduz posicao. Se o venue nao tiver reduce-only nativo, e o conector que o garante — e tem de o declarar.',
    )
    reverter: bool = Field(
        ...,
        description="A VIRADA (aditivo na 1.10.0): `true` diz ao conector para FECHAR a posicao viva e ABRIR a do lado declarado em `lado`, com o tamanho do mandato. Obrigatorio porque a ausencia nao e' um valor: `false` diz «nao e' reversao» e a ausencia diria «nao foi declarado» (D4). Contradicao impossivel: `reverter: true` com `reduce_only: true` RECUSA (`reversao_com_reduce_only`) — «reduz, nunca inverte» e «inverte» nao cabem na mesma ordem.",
    )
    posicao_pct: forma_schema.DecimalPositivo = Field(
        ...,
        description="O TAMANHO RELATIVO A' POSICAO VIVA (nao ao saldo) — a REDUCAO PARCIAL (aditivo na 1.11.0). `1` e' a posicao INTEIRA, e e' o valor de uma ordem que NAO e' uma reducao parcial: «nao e' parcial» e' um valor DECLARADO (como o `reverter: false`), e a ausencia diria «nao foi declarado» (D4) — por isso o campo e' OBRIGATORIO. Abaixo de `1`, a ordem fecha essa fraccao do que esta' aberto («reduz metade» = `0.5`), exige `reduce_only: true` (quem reduz nunca inverte), e quem a converte em quantidade e' o CONECTOR, que le' a posicao viva do venue (RN-B0: a boleta nao leva quantidade). Nenhum setup do repositorio emite reducao parcial: o campo entra no vocabulario ANTES do primeiro uso.",
    )
    referencia_do_cliente: forma_schema.Correlacao = Field(
        ...,
        description='Idempotencia: reenviar com a MESMA referencia nao pode criar segunda ordem (RN-C4).',
    )
    marca_de_posse: forma_schema.MarcaDePosse
