# generated by datamodel-codegen:
#   filename:  boleta.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Tipo(Enum):
    mercado = 'mercado'
    limite = 'limite'
    stop = 'stop'
    stop_limite = 'stop_limite'
    mercado_por_faixa = 'mercado_por_faixa'


class Parcial(Enum):
    tudo_ou_nada = 'tudo_ou_nada'
    o_que_der = 'o_que_der'


class DestinoDoResto(Enum):
    agressivo = 'agressivo'
    cancelar = 'cancelar'


class BoletaUniversal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    lado: forma_schema.Lado
    tipo: Tipo = Field(
        ...,
        description='Tipo NEUTRO de ordem. Se o manifesto nao declarar esta capacidade, a boleta e recusada — nao adaptada.',
    )
    saldo_pct: forma_schema.DecimalPositivo = Field(
        ...,
        description='Percentagem do SALDO. E um valor do dono (RN-A1), nao uma constante do programa.',
    )
    alavancagem: forma_schema.DecimalPositivo = Field(
        ..., description='Multiplo de alavancagem pedido.'
    )
    stop_pct: forma_schema.DecimalPositivo | None = Field(
        None,
        description='Distancia de stop em percentagem de MOVIMENTO (nao em pontos). Ausente = este setup nao usa stop (RN-S3).',
    )
    tp_pct: forma_schema.DecimalPositivo | None = Field(
        None,
        description='Distancia de lucro em percentagem de MOVIMENTO. Ausente = sem alvo declarado.',
    )
    parcial: Parcial = Field(
        ...,
        description='Obrigatoria (RN-B6): o que fazer se so parte da quantidade couber. Escolha do setup, nunca do conector.',
    )
    desvio_maximo: forma_schema.DecimalPositivo = Field(
        ..., description='Desvio maximo de preco aceite, em percentagem de movimento.'
    )
    prazo_da_passiva_ms: forma_schema.DuracaoMs = Field(
        ...,
        description='Quanto tempo a parte passiva da ordem espera antes de o destino do resto decidir.',
    )
    destino_do_resto: DestinoDoResto = Field(
        ...,
        description='O que fazer com o que ficou por executar quando o prazo da passiva acaba.',
    )
    reduce_only: bool = Field(
        ...,
        description='So reduz posicao. Se o venue nao tiver reduce-only nativo, e o conector que o garante — e tem de o declarar.',
    )
    referencia_do_cliente: forma_schema.Correlacao = Field(
        ...,
        description='Idempotencia: reenviar com a MESMA referencia nao pode criar segunda ordem (RN-C4).',
    )
    marca_de_posse: forma_schema.MarcaDePosse
