# generated by datamodel-codegen:
#   filename:  comando.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr

from ._defs import forma_schema


class ComandoDoVigia(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verbo: forma_schema.VerboDoVigia
    autor: forma_schema.Autor
    pedido_id: forma_schema.Correlacao
    motivo: constr(min_length=1, max_length=200) | None = Field(
        None,
        description='So no `nova_sessao`: a razao de abrir sessao nova e do dono e fica registrada (RN-V10).',
    )
