# generated by datamodel-codegen:
#   filename:  decisao_do_encerramento.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ._defs import forma_schema


class ADecisaoDoDonoSobreOEncerramento(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pedido_id: forma_schema.Correlacao
    resposta: forma_schema.RespostaDoEncerramento
