# generated by datamodel-codegen:
#   filename:  desfecho.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from . import resolucao_schema
from ._defs import forma_schema


class Classificacao(Enum):
    aceite = 'aceite'
    parcial = 'parcial'
    desconhecido = 'desconhecido'
    recusado = 'recusado'


class DesfechoDaOrdem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classificacao: Classificacao = Field(
        ...,
        description='Aceite, parcial, desconhecido ou recusado. Um valor fora destes quatro nao existe no contrato.',
    )
    motivo: forma_schema.Motivo | None = Field(
        None,
        description='Obrigatorio quando a classificacao e recusado. Identificador do vocabulario, nunca texto livre.',
    )
    resolucao: resolucao_schema.ResolucaoDoConector | None = Field(
        None,
        description='A resolucao faz parte do desfecho (RN-C10) SEMPRE que existiu uma: nao se resolve o que nunca se chegou a resolver. Recusa antes de resolver (capacidade nao declarada, por exemplo) traz motivo e nao traz resolucao.',
    )
    resposta_do_venue: dict[str, Any] = Field(
        ...,
        description='A resposta BRUTA do venue. O contrato nao a interpreta — o registo guarda-a como chegou, para que nada dependa de interpretacao (FR-021).',
    )
