# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Tipo(Enum):
    mercado = 'mercado'
    proposta = 'proposta'
    boleta = 'boleta'
    resolucao = 'resolucao'
    desfecho = 'desfecho'
    manifesto = 'manifesto'
    historico = 'historico'


class EnvelopeDaMensagem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contrato: forma_schema.Versao
    tipo: Tipo = Field(
        ..., description='O tipo decide qual e o corpo. Nao ha tipo sem schema.'
    )
    id: forma_schema.Correlacao
    carga: dict[str, Any]
