# generated by datamodel-codegen:
#   filename:  historico.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr

from ._defs import forma_schema


class Lado(Enum):
    buy = 'buy'
    sell = 'sell'


class Execuco(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    referencia_do_cliente: forma_schema.Correlacao
    marca_de_posse: forma_schema.MarcaDePosse
    instante_ms: forma_schema.InstanteMs
    lado: Lado
    quantidade: forma_schema.DecimalPositivo
    preco: forma_schema.DecimalPositivo
    taxa: forma_schema.DecimalNaoNegativo = Field(
        ..., description='Custo da execucao, como o venue o cobra.'
    )
    funding: forma_schema.Decimal | None = Field(
        None,
        description='Funding da execucao, em campo PROPRIO. Ausente quando o venue nao o reporta por execucao.',
    )


class HistoricoDoVenue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    moeda: constr(pattern=r'^[A-Z]{3}$')
    instante_ms: forma_schema.InstanteMs
    resultado_realizado: forma_schema.Decimal = Field(
        ..., description='Como o venue o reporta. A mesa mostra, nao reconstroi.'
    )
    execucoes: list[Execuco] = Field(..., min_length=1)
