# generated by datamodel-codegen:
#   filename:  historico.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Lado(Enum):
    buy = 'buy'
    sell = 'sell'


class Execuco(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    referencia_do_cliente: forma_schema.Correlacao | None = Field(
        None,
        description='A referencia que o VENUE guardou para esta execucao. OPCIONAL desde a 1.5.0, e a razao e MEDIDA: a Hyperliquid nao guardou `cloid` nenhum nas 415 de 415 ordens desta conta (o `cloid` que a mesa usa e DERIVADO da referencia, de mao unica — nunca se le de volta). Ausente = o venue nao a guardou; a chave NAO se escreve, e ausencia NUNCA vira valor nenhum (nem zero, nem cadeia vazia).',
    )
    marca_de_posse: forma_schema.MarcaDePosseDoVenue | None = Field(
        None,
        description='A marca de posse que o venue guardou, na forma que o MANIFESTO dele declara. Duas formas, e so duas (1.5.0): o inteiro de 31 bits e o `cloid` (0x + 32 hexadecimais). OPCIONAL desde a 1.5.0: medido nesta conta, o venue NAO guardou marca nenhuma (as 415 de 415 ordens vieram com `cloid` nulo), e exigi-la obrigaria a mesa a inventar uma — ausente e o que se escreve, nunca zero.',
    )
    instante_ms: forma_schema.InstanteMs
    lado: Lado
    quantidade: forma_schema.DecimalPositivo
    preco: forma_schema.DecimalPositivo
    taxa: forma_schema.DecimalNaoNegativo = Field(
        ..., description='Custo da execucao, como o venue o cobra.'
    )
    funding: forma_schema.Decimal | None = Field(
        None,
        description='Funding da execucao, em campo PROPRIO. OPCIONAL por execucao: ausente quando o venue nao o reporta por execucao — e a Hyperliquid NAO o reporta por execucao (medido), pelo que ausente NAO e zero. Um zero aqui seria um custo medido, e nao ha nenhum a medir.',
    )


class HistoricoDoVenue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    moeda: forma_schema.Moeda = Field(
        ...,
        description='A moeda em que o venue cobra a taxa, como ele a ESCREVE. A forma vive num so sitio (`_defs/forma.schema.json#/$defs/moeda`) e admite de UM a ONZE caracteres alfanumericos, maiusculas ou minusculas, desde a 1.6.0 — medido contra o universo real do venue (1863 simbolos distintos, comprimentos de 1 a 11, com digitos e minusculas). `USDC` nao e `USD`: nada se normaliza.',
    )
    instante_ms: forma_schema.InstanteMs
    resultado_realizado: forma_schema.Decimal | None = Field(
        None,
        description='O resultado realizado DO INSTRUMENTO, como o venue o reporta. A mesa mostra, nao reconstroi. OPCIONAL desde a 1.5.0, e a razao e MEDIDA: a fonte deste numero e POR EXECUCAO — a Hyperliquid publica `closedPnl` em `userFills` (cada execucao com o seu, em campo PROPRIO da leitura) e NAO um numero por instrumento. Somar as parcelas para preencher este campo seria RECONSTRUIR o resultado, o defeito que FR-018/RN-H14 proibem: por isso o campo fica AUSENTE quando o venue nao o publica, e nunca zero.',
    )
    execucoes: list[Execuco] = Field(..., min_length=1)
