# generated by datamodel-codegen:
#   filename:  manifesto.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, conint

from ._defs import forma_schema


class Conector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nome: forma_schema.NomeDePlugin
    versao: forma_schema.Versao


class AlavancagemPorEscalaoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ate: forma_schema.DecimalPositivo
    maxima: forma_schema.DecimalPositivo


class Instrumento(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    simbolo: forma_schema.Instrumento
    minimo: forma_schema.DecimalPositivo
    passo: forma_schema.DecimalPositivo
    tick: forma_schema.DecimalPositivo
    alavancagem_maxima: forma_schema.DecimalPositivo
    alavancagem_por_escalao: list[AlavancagemPorEscalaoItem] | None = Field(
        None,
        description='Escaloes de valor com maxima proprio. Ausente = vale a maxima unica.',
    )


class ModosDeMargemEnum(Enum):
    cruzado = 'cruzado'
    isolado = 'isolado'


class ModeloDePosicao(Enum):
    netting = 'netting'
    hedging = 'hedging'
    exchange = 'exchange'


class TiposDeOrdemEnum(Enum):
    mercado = 'mercado'
    limite = 'limite'
    stop = 'stop'
    stop_limite = 'stop_limite'
    mercado_por_faixa = 'mercado_por_faixa'


class ParcialSuportadaEnum(Enum):
    tudo_ou_nada = 'tudo_ou_nada'
    o_que_der = 'o_que_der'


class RelogioDeFechoDeBarra(Enum):
    horario = 'horario'
    meia_noite_utc = 'meia_noite_utc'
    continuo = 'continuo'
    desconhecido = 'desconhecido'


class MarcaDePosse(Enum):
    cloid = 'cloid'
    clientOrderId = 'clientOrderId'
    magic = 'magic'
    comment = 'comment'
    nenhuma = 'nenhuma'


class ManifestoDoConector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conector: Conector
    versao: forma_schema.Versao = Field(
        ...,
        description='A versao do CONTRATO que este conector implementa (RN-E18): conferida por igualdade exacta.',
    )
    instrumentos: list[Instrumento] = Field(
        ...,
        description='As unidades declaradas por instrumento. Sem unidade declarada nao ha resolucao possivel.',
        min_length=1,
    )
    sabe_ajustar_alavancagem: bool
    modos_de_margem: list[ModosDeMargemEnum] = Field(..., min_length=1)
    teto_de_valor_por_ordem: forma_schema.DecimalPositivo = Field(
        ...,
        description='Teto de valor por ordem imposto pelo venue. Nao e o limite do dono: e o do venue, e a mesa confere contra ele antes de enviar.',
    )
    modelo_de_posicao: ModeloDePosicao
    tipos_de_ordem: list[TiposDeOrdemEnum] = Field(..., min_length=1)
    parcial_suportada: list[ParcialSuportadaEnum] = Field(..., min_length=1)
    desvio_maximo: forma_schema.DecimalPositivo = Field(
        ...,
        description='Desvio maximo que o venue aceita, em percentagem de movimento.',
    )
    reduce_only_nativo: bool
    stop_anexo: bool = Field(
        ...,
        description='Se o venue sabe prender stop a uma posicao (o que muda o desfecho de uma parcial).',
    )
    profundidade_de_livro: conint(ge=0)
    funding: bool
    relogio_de_fecho_de_barra: RelogioDeFechoDeBarra
    idempotencia: bool = Field(
        ...,
        description='Se o venue garante nao duplicar por referencia repetida. Sem isto, a mesa reconcilia ANTES de reenviar (RN-C4).',
    )
    marca_de_posse: MarcaDePosse = Field(
        ...,
        description="A forma que este venue aceita. 'nenhuma' e declaracao valida — e a mesa di-lo, em vez de fingir uma marca que nao existe (FR-027).",
    )
    marca_liga_ordem_a_posicao: bool
    estado_do_mercado: bool = Field(
        ...,
        description='Se o venue sabe dizer se o mercado esta aberto (RN-D8). Sem isto, mercado fechado so se detecta pela ausencia de leitura.',
    )
