# generated by datamodel-codegen:
#   filename:  manifesto.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, conint

from ._defs import forma_schema


class Conector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nome: forma_schema.NomeDePlugin
    versao: forma_schema.Versao


class AlavancagemPorEscalaoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    de: forma_schema.DecimalNaoNegativo = Field(
        ...,
        description='Limite INFERIOR do escalao. `0` e valor legitimo: o primeiro escalao do venue comeca em `0.0` (medido) — e um `decimal_positivo` recusava-o, que foi o defeito que esta emenda corrige.',
    )
    maxima: forma_schema.DecimalPositivo


class Instrumento(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    simbolo: forma_schema.Instrumento
    minimo: forma_schema.DecimalPositivo
    passo: forma_schema.DecimalPositivo
    tick: forma_schema.DecimalPositivo
    alavancagem_maxima: forma_schema.DecimalPositivo
    deslistado: bool | None = Field(
        None,
        description='O venue lista o instrumento como DESLISTADO (`isDelisted`). Ausente = o venue nao o declarou para este instrumento — e ausencia NAO e `false`: o venue de teste so escreve a chave quando ela e verdadeira (medido: 54 de 212). Um mandato que nomeie um deslistado RECUSA (`instrumento_deslistado_no_venue`); o campo existe para o facto ter onde ser declarado, e para a mesa poder recusar uma boleta sobre um manifesto que o traga.',
    )
    funding_intervalo_horas: conint(ge=1) | None = Field(
        None,
        description='De quanto em quanto tempo o venue cobra funding, em HORAS, como o venue o declara (`predictedFundings()[coin][HlPerp].fundingIntervalHours`, medido: 1 para os 212 instrumentos). POR INSTRUMENTO, e nao por venue: e onde o venue o declara, e a mesma resposta traz 8 horas para os perps de outras corretoras. Ausente = nao declarado para este instrumento.',
    )
    alavancagem_por_escalao: list[AlavancagemPorEscalaoItem] | None = Field(
        None,
        description='Escaloes de valor com maxima proprio. Ausente = vale a maxima unica. Cada escalao declara o seu limite INFERIOR (`de`) — a forma como o venue o da (`marginTiers[].lowerBound`, com o primeiro a `0.0`): o escalao de um valor e o maior `de` que nao o excede. O primeiro escalao a zero e legitimo, e e o que cobre os valores baixos; um valor que nenhum `de` cubra nao tem escalao, e a conferencia RECUSA.',
        min_length=1,
    )


class ModosDeMargemEnum(Enum):
    cruzado = 'cruzado'
    isolado = 'isolado'


class ModeloDePosicao(Enum):
    netting = 'netting'
    hedging = 'hedging'
    exchange = 'exchange'


class TiposDeOrdemEnum(Enum):
    mercado = 'mercado'
    limite = 'limite'
    stop = 'stop'
    stop_limite = 'stop_limite'
    mercado_por_faixa = 'mercado_por_faixa'


class ParcialSuportadaEnum(Enum):
    tudo_ou_nada = 'tudo_ou_nada'
    o_que_der = 'o_que_der'


class RelogioDeFechoDeBarra(Enum):
    horario = 'horario'
    meia_noite_utc = 'meia_noite_utc'
    continuo = 'continuo'
    desconhecido = 'desconhecido'


class MarcaDePosse(Enum):
    cloid = 'cloid'
    clientOrderId = 'clientOrderId'
    magic = 'magic'
    comment = 'comment'
    nenhuma = 'nenhuma'


class ManifestoDoConector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conector: Conector
    versao: forma_schema.Versao = Field(
        ...,
        description='A versao do CONTRATO que este conector implementa (RN-E18): conferida por igualdade exacta.',
    )
    instrumentos: list[Instrumento] = Field(
        ...,
        description='As unidades declaradas por instrumento. Sem unidade declarada nao ha resolucao possivel.',
        min_length=1,
    )
    sabe_ajustar_alavancagem: bool
    modos_de_margem: list[ModosDeMargemEnum] = Field(..., min_length=1)
    minimo_de_valor_por_ordem: forma_schema.DecimalPositivo = Field(
        ...,
        description='PISO de valor por ordem imposto pelo venue: abaixo dele o venue RECUSA a ordem. Nao e o limite do dono, nem um tecto — e o minimo OBSERVADO no venue (Hyperliquid: $10, §5.d da regra de negocio; quem o mede e a bateria de conformidade). A mesa confere-o antes de enviar, e igual ao minimo PASSA.',
    )
    maximo_de_valor_por_ordem: forma_schema.DecimalPositivo | None = Field(
        None,
        description='TECTO de valor por ordem, quando o venue o declara. ADITIVO na 1.4.0: o campo que existia chamava-se `teto_de_valor_por_ordem` e carregava o MINIMO — o nome mentia. Ausente = o venue nao declarou tecto nenhum (ausencia nao e «ilimitado»: e nao medido), e a mesa nao inventa um.',
    )
    modelo_de_posicao: ModeloDePosicao
    tipos_de_ordem: list[TiposDeOrdemEnum] = Field(..., min_length=1)
    parcial_suportada: list[ParcialSuportadaEnum] = Field(..., min_length=1)
    desvio_maximo: forma_schema.DecimalPositivo = Field(
        ...,
        description='Desvio maximo que o venue aceita, em percentagem de movimento.',
    )
    reduce_only_suportado: bool = Field(
        ...,
        description='Se o pedido reduce_only pode ser HONRADO — nativo ou emulado pelo conector. Nao diz o mecanismo: diz a capacidade. Sem esta declaracao, a mesa recusa a boleta em vez de mandar um reduce-only que o venue pode ignorar.',
    )
    stop_anexo: bool = Field(
        ...,
        description='Se o venue sabe prender stop a uma posicao (o que muda o desfecho de uma parcial).',
    )
    profundidade_de_livro: conint(ge=0)
    funding: bool
    relogio_de_fecho_de_barra: RelogioDeFechoDeBarra
    idempotencia: bool = Field(
        ...,
        description='Se o venue garante nao duplicar por referencia repetida. Sem isto, a mesa reconcilia ANTES de reenviar (RN-C4).',
    )
    marca_de_posse: MarcaDePosse = Field(
        ...,
        description="A forma que este venue aceita. 'nenhuma' e declaracao valida — e a mesa di-lo, em vez de fingir uma marca que nao existe (FR-027).",
    )
    marca_liga_ordem_a_posicao: bool
    estado_do_mercado: bool = Field(
        ...,
        description='Se o venue sabe dizer se o mercado esta aberto (RN-D8). Sem isto, mercado fechado so se detecta pela ausencia de leitura.',
    )
