# generated by datamodel-codegen:
#   filename:  mercado.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from ._defs import forma_schema


class Estado(Enum):
    aberto = 'aberto'
    fechado = 'fechado'


class Lado(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preco: forma_schema.DecimalPositivo
    tamanho: forma_schema.DecimalPositivo


class Livro(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lados: list[Lado] = Field(..., min_length=1)
    profundidade: conint(ge=1) = Field(
        ..., description='Profundidade DECLARADA: o setup sabe o que nao ve.'
    )


class Lado3(Enum):
    buy = 'buy'
    sell = 'sell'


class OrdensAberta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    ordem: constr(min_length=1) = Field(
        ...,
        description="O identificador da ordem NO VENUE (`oid`). E' por ele que a mesa e o humano falam da MESMA ordem.",
    )
    lado: Lado3
    preco: forma_schema.DecimalPositivo
    unidades: forma_schema.DecimalPositivo
    marca_de_posse: forma_schema.MarcaDePosseDoVenue | None = None


class Posicao(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lado: Lado3
    unidades: forma_schema.DecimalPositivo
    preco_medio: forma_schema.DecimalPositivo
    marca_de_posse: forma_schema.MarcaDePosse | None = None


class Funding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taxa: forma_schema.Decimal
    instante_ms: forma_schema.InstanteMs


class ObjectoDeMercado(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instrumento: forma_schema.Instrumento
    tempo_do_venue_ms: forma_schema.InstanteMs
    idade_do_dado_ms: forma_schema.DuracaoMs
    estado: Estado = Field(
        ..., description='Mercado fechado e ESTADO, nao erro (RN-D8).'
    )
    bid: forma_schema.DecimalPositivo | None = None
    ask: forma_schema.DecimalPositivo | None = None
    ultimo: forma_schema.DecimalPositivo | None = None
    livro: Livro | None = None
    ordens_abertas: list[OrdensAberta] = Field(
        ...,
        description="AS ORDENS VIVAS NO VENUE — o que existe na conta e nao e' posicao: o que ficou pendurado, o que ficou por cancelar, o que outro dedo pos. OBRIGATORIA, e LISTA VAZIA NAO E' O MESMO QUE AUSENTE: `[]` diz 'perguntei, e nao ha' nenhuma'; ausente seria 'nao perguntei'. Quem nao conseguiu perguntar NAO PRODUZ leitura (recusa nomeada) — uma lista vazia inventada aqui faria a mesa achar que a conta esta' limpa quando nao esta'.",
    )
    posicao: Posicao | None = Field(
        None,
        description='Ausente = sem posicao. A posse le-se do VENUE, pela marca (RN-T16.1).',
    )
    equity: forma_schema.Decimal = Field(
        ...,
        description='Saldo com nao realizado: e sobre isto que o circuit breaker mede (RN-M3).',
    )
    funding: Funding | None = None
