# generated by datamodel-codegen:
#   filename:  pergunta_do_encerramento.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr

from ._defs import forma_schema


class Numeros(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    posicao: forma_schema.Decimal
    nocional: forma_schema.DecimalNaoNegativo
    margem: forma_schema.DecimalNaoNegativo
    distancia_de_liquidacao: forma_schema.DecimalNaoNegativo
    resultado_nao_realizado: forma_schema.Decimal


class APerguntaDoEncerramento(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pedido_id: forma_schema.Correlacao
    opcoes: list[forma_schema.RespostaDoEncerramento] = Field(
        ..., max_length=2, min_length=2
    )
    prazo_de_resposta_ms: forma_schema.DuracaoMs = Field(
        ...,
        description='A chave do dono (setup.prazo_de_resposta_ms, RN-A3): quanto a mesa espera antes de voltar a operar com o `stop` pendente (RN-V9.1).',
    )
    aviso_de_manter: constr(min_length=1, max_length=400) = Field(
        ...,
        description='Obrigatorio: a pergunta so existe quando ha o que decidir, e um aviso vazio seria um aviso que nao avisa. `null` nao existe neste contrato (D4).',
    )
    numeros: Numeros = Field(
        ...,
        description='Cinco numeros do venue. Um venue que nao saiba um deles e materia da bateria de conformidade (RN-C6) e de um DEFEITO declarado - nao de um `null` silencioso.',
    )
