# generated by datamodel-codegen:
#   filename:  proposta.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Setup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nome: forma_schema.NomeDePlugin
    versao: forma_schema.Versao


class Relogio(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proxima_consulta_ms: forma_schema.DuracaoMs


class PropostaDoSetup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    setup: Setup = Field(..., description='A assinatura que entra no registo (RN-S7).')
    lado: forma_schema.Lado
    relogio: Relogio | None = Field(
        None,
        description='O setup pode adiantar o prazo do seu template. Ausente, vale o prazo do template (RN-S2, RN-S3).',
    )
