# generated by datamodel-codegen:
#   filename:  proposta.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class Setup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nome: forma_schema.NomeDePlugin
    versao: forma_schema.Versao


class Relogio(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proxima_consulta_ms: forma_schema.DuracaoMs


class PropostaDoSetup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    setup: Setup = Field(..., description='A assinatura que entra no registo (RN-S7).')
    lado: forma_schema.Lado
    barra_ms: forma_schema.InstanteMs = Field(
        ...,
        description="A BARRA DO SINAL: o instante da ABERTURA da barra FECHADA sobre a qual o setup decidiu (ms UTC, do relogio do VENUE). E obrigatoria porque sem ela a proposta nao se situa no tempo: a mesa nao pode distinguir 'a proposta que acabou de nascer' de 'a proposta da barra passada, que ja foi executada', e uma entrada perdida ou repetida nao se explica depois. O setup e o unico que sabe em que barra decidiu — por isso e ele que o declara, e nao quem o le.",
    )
    relogio: Relogio | None = Field(
        None,
        description='O setup pode adiantar o prazo do seu template. Ausente, vale o prazo do template (RN-S2, RN-S3).',
    )
