# generated by datamodel-codegen:
#   filename:  resolucao.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from ._defs import forma_schema


class ResolucaoDoConector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    quantidade: forma_schema.DecimalPositivo = Field(
        ...,
        description='Na unidade do instrumento, como o manifesto a declara. Nunca arredondada em silencio.',
    )
    nocional: forma_schema.DecimalPositivo = Field(
        ...,
        description='Valor da posicao. E contra o teto do manifesto que se confere.',
    )
    margem_empenhada: forma_schema.DecimalPositivo = Field(
        ..., description='Margem que fica presa. E o que o mandato soma (RN-M5).'
    )
    alavancagem_efectiva: forma_schema.DecimalPositivo = Field(
        ...,
        description='A que o venue realmente aplica — pode nao ser a pedida, e entao a resolucao mostra a diferenca.',
    )
    preco_de_liquidacao: forma_schema.DecimalNaoNegativo = Field(
        ...,
        description='Preco a que a posicao seria liquidada (RN-M4.13). Zero e valor LEGITIMO: a alavancagem 1 so liquida a preco zero, e o contrato nao pode chamar invalido ao que e verdade.',
    )
