# generated by datamodel-codegen:
#   filename:  resposta_de_comando.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ._defs import forma_schema


class Transicao(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    de: forma_schema.EstadoDaMesa
    para: forma_schema.EstadoDaMesa


class RespostaDaMesaAoComando(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pedido_id: forma_schema.Correlacao
    aceito: bool
    motivo: forma_schema.MotivoDeComando | None = None
    efeito: forma_schema.EfeitoDeComando | None = None
    transicao: Transicao
    instante_ms: forma_schema.InstanteDaMesaMs
