# generated by datamodel-codegen:
#   filename:  _defs/forma.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import Field, RootModel, conint, constr


class FormaPartilhadaDoContratoNeutro(RootModel[Any]):
    root: Any = Field(
        ...,
        description='As definições que TODO o contrato usa. Decisões D4 (decimal textual), D5 (contrato fechado), D6 (marca de 31 bits), D7 (versão por igualdade exacta).',
        title='Forma partilhada do contrato neutro',
    )


class VerboDoVigia(StrEnum):
    start = 'start'
    pause = 'pause'
    stop = 'stop'
    reset = 'reset'
    nova_sessao = 'nova_sessao'


class Autor(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64) = Field(
        ..., description='Quem mandou. Um verbo sem autor nao se pode auditar (RN-V4).'
    )


class EstadoDaMesa(StrEnum):
    parada = 'parada'
    em_operacao = 'em_operacao'
    pausada = 'pausada'
    encerrando = 'encerrando'


class InstanteDaMesaMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Instante em milissegundos, do relogio da MESA - nao do venue (RN-M4.9: quem recebe e que carimba; instante de fora nao se usa, senao quem chama escolhe o lugar na fila).',
    )


class MotivoDeComando(StrEnum):
    mesa_ja_em_operacao = 'mesa_ja_em_operacao'
    mesa_parada_nada_a_pausar = 'mesa_parada_nada_a_pausar'
    mesa_ja_pausada = 'mesa_ja_pausada'
    mesa_ja_parada = 'mesa_ja_parada'
    mesa_em_encerramento = 'mesa_em_encerramento'
    pedido_repetido = 'pedido_repetido'
    sessao_inibida = 'sessao_inibida'
    porta_do_arranque_falhou = 'porta_do_arranque_falhou'
    liquidacao_em_curso = 'liquidacao_em_curso'
    sessao_nova_com_posicao_viva = 'sessao_nova_com_posicao_viva'
    mesa_precisa_parar_para_sessao_nova = 'mesa_precisa_parar_para_sessao_nova'
    verbo_desconhecido = 'verbo_desconhecido'
    comando_com_campo_a_mais = 'comando_com_campo_a_mais'
    comando_incompleto = 'comando_incompleto'
    comando_com_tipo_invalido = 'comando_com_tipo_invalido'
    versao_do_contrato_divergente = 'versao_do_contrato_divergente'
    posicao_desconhecida = 'posicao_desconhecida'
    prazo_de_resposta_nao_declarado = 'prazo_de_resposta_nao_declarado'
    numeros_da_corretora_ausentes = 'numeros_da_corretora_ausentes'
    decisao_sem_pergunta = 'decisao_sem_pergunta'
    equity_de_partida_nao_lido = 'equity_de_partida_nao_lido'
    unidade_de_comparacao_nao_declarada = 'unidade_de_comparacao_nao_declarada'


class EfeitoDeComando(StrEnum):
    sessao_nova_gravada = 'sessao_nova_gravada'
    reset_nao_toca_em_nada = 'reset_nao_toca_em_nada'
    resumo_do_encerramento_apresentado = 'resumo_do_encerramento_apresentado'
    stop_pendente_por_prazo = 'stop_pendente_por_prazo'
    parada_com_posicao_viva = 'parada_com_posicao_viva'
    liquidacao_em_curso = 'liquidacao_em_curso'


class RespostaDoEncerramento(StrEnum):
    fechar_a_mercado = 'fechar_a_mercado'
    manter = 'manter'


class Decimal(RootModel[constr(pattern=r'^-?(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^-?(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description="Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.",
    )


class DecimalNaoNegativo(RootModel[constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description='Decimal textual sem sinal — para grandezas que não podem ser negativas (idade, profundidade, quantidade, nocional).',
    )


class DecimalPositivo(
    RootModel[constr(pattern=r'^(0*\.[0-9]*[1-9][0-9]*|[1-9][0-9]*(\.[0-9]+)?)$')]
):
    root: constr(pattern=r'^(0*\.[0-9]*[1-9][0-9]*|[1-9][0-9]*(\.[0-9]+)?)$') = Field(
        ...,
        description="Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.",
    )


class Percentagem(RootModel[constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description='Percentagem como decimal textual, sem sinal. O valor é um número do dono (RN-A1), não uma constante do programa.',
    )


class InstanteMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).',
    )


class DuracaoMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(..., description='Duração em milissegundos.')


class Versao(RootModel[constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')]):
    root: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ...,
        description='Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).',
    )


class Correlacao(RootModel[constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9._:/-]{0,63}$')]):
    root: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9._:/-]{0,63}$') = Field(
        ...,
        description="Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.",
    )


class Instrumento(RootModel[constr(pattern=r'^[A-Z0-9][A-Z0-9._/-]{1,31}$')]):
    root: constr(pattern=r'^[A-Z0-9][A-Z0-9._/-]{1,31}$') = Field(
        ..., description='Símbolo do instrumento, como o venue o escreve.'
    )


class NomeDePlugin(RootModel[constr(pattern=r'^[a-z][a-z0-9_]{1,31}$')]):
    root: constr(pattern=r'^[a-z][a-z0-9_]{1,31}$') = Field(
        ..., description='Nome de setup ou conector: minúsculas, com underscore.'
    )


class Motivo(StrEnum):
    versao_do_contrato_divergente = 'versao_do_contrato_divergente'
    enquadramento_invalido = 'enquadramento_invalido'
    campo_obrigatorio_ausente = 'campo_obrigatorio_ausente'
    valor_nulo_nao_permitido = 'valor_nulo_nao_permitido'
    campo_desconhecido = 'campo_desconhecido'
    campo_em_unidade_de_corretora = 'campo_em_unidade_de_corretora'
    parcial_nao_declarada = 'parcial_nao_declarada'
    formato_invalido = 'formato_invalido'
    tipo_invalido = 'tipo_invalido'
    valor_fora_do_conjunto = 'valor_fora_do_conjunto'
    valor_fora_da_banda = 'valor_fora_da_banda'
    capacidade_nao_declarada = 'capacidade_nao_declarada'
    instrumento_desconhecido_no_manifesto = 'instrumento_desconhecido_no_manifesto'
    minimo_do_instrumento_acima_da_banda = 'minimo_do_instrumento_acima_da_banda'
    prazo_excedido = 'prazo_excedido'
    desfecho_nao_reconhecido = 'desfecho_nao_reconhecido'


class MarcaDePosse(RootModel[conint(ge=0, le=2147483647)]):
    root: conint(ge=0, le=2147483647) = Field(
        ...,
        description='Marca de posse: inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment.',
    )


class Lado(StrEnum):
    buy = 'buy'
    sell = 'sell'
    hold = 'hold'
    caixa = 'caixa'
