# generated by datamodel-codegen:
#   filename:  _defs/forma.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import Field, RootModel, conint, constr


class FormaPartilhadaDoContratoNeutro(RootModel[Any]):
    root: Any = Field(
        ...,
        description='As definições que TODO o contrato usa. Decisões D4 (decimal textual), D5 (contrato fechado), D6 (marca de 31 bits), D7 (versão por igualdade exacta).',
        title='Forma partilhada do contrato neutro',
    )


class VerboDoVigia(StrEnum):
    start = 'start'
    pause = 'pause'
    stop = 'stop'
    reset = 'reset'
    nova_sessao = 'nova_sessao'


class Autor(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64) = Field(
        ..., description='Quem mandou. Um verbo sem autor nao se pode auditar (RN-V4).'
    )


class EstadoDaMesa(StrEnum):
    parada = 'parada'
    em_operacao = 'em_operacao'
    pausada = 'pausada'
    encerrando = 'encerrando'


class InstanteDaMesaMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Instante em milissegundos, do relogio da MESA - nao do venue (RN-M4.9: quem recebe e que carimba; instante de fora nao se usa, senao quem chama escolhe o lugar na fila).',
    )


class MotivoDeComando(StrEnum):
    mesa_ja_em_operacao = 'mesa_ja_em_operacao'
    mesa_parada_nada_a_pausar = 'mesa_parada_nada_a_pausar'
    mesa_ja_pausada = 'mesa_ja_pausada'
    mesa_ja_parada = 'mesa_ja_parada'
    mesa_em_encerramento = 'mesa_em_encerramento'
    pedido_repetido = 'pedido_repetido'
    sessao_inibida = 'sessao_inibida'
    porta_do_arranque_falhou = 'porta_do_arranque_falhou'
    liquidacao_em_curso = 'liquidacao_em_curso'
    sessao_nova_com_posicao_viva = 'sessao_nova_com_posicao_viva'
    mesa_precisa_parar_para_sessao_nova = 'mesa_precisa_parar_para_sessao_nova'
    verbo_desconhecido = 'verbo_desconhecido'
    comando_com_campo_a_mais = 'comando_com_campo_a_mais'
    comando_incompleto = 'comando_incompleto'
    comando_com_tipo_invalido = 'comando_com_tipo_invalido'
    versao_do_contrato_divergente = 'versao_do_contrato_divergente'
    posicao_desconhecida = 'posicao_desconhecida'
    prazo_de_resposta_nao_declarado = 'prazo_de_resposta_nao_declarado'
    numeros_da_corretora_ausentes = 'numeros_da_corretora_ausentes'
    decisao_sem_pergunta = 'decisao_sem_pergunta'
    equity_de_partida_nao_lido = 'equity_de_partida_nao_lido'
    unidade_de_comparacao_nao_declarada = 'unidade_de_comparacao_nao_declarada'


class EfeitoDeComando(StrEnum):
    sessao_nova_gravada = 'sessao_nova_gravada'
    reset_nao_toca_em_nada = 'reset_nao_toca_em_nada'
    resumo_do_encerramento_apresentado = 'resumo_do_encerramento_apresentado'
    stop_pendente_por_prazo = 'stop_pendente_por_prazo'
    parada_com_posicao_viva = 'parada_com_posicao_viva'
    liquidacao_em_curso = 'liquidacao_em_curso'


class RespostaDoEncerramento(StrEnum):
    fechar_a_mercado = 'fechar_a_mercado'
    manter = 'manter'


class Decimal(RootModel[constr(pattern=r'^-?(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^-?(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description="Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.",
    )


class DecimalNaoNegativo(RootModel[constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description='Decimal textual sem sinal — para grandezas que não podem ser negativas (idade, profundidade, quantidade, nocional).',
    )


class DecimalPositivo(
    RootModel[constr(pattern=r'^(0*\.[0-9]*[1-9][0-9]*|[1-9][0-9]*(\.[0-9]+)?)$')]
):
    root: constr(pattern=r'^(0*\.[0-9]*[1-9][0-9]*|[1-9][0-9]*(\.[0-9]+)?)$') = Field(
        ...,
        description="Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.",
    )


class Percentagem(RootModel[constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$')]):
    root: constr(pattern=r'^(0|[1-9][0-9]*)(\.[0-9]+)?$') = Field(
        ...,
        description='Percentagem como decimal textual, sem sinal. O valor é um número do dono (RN-A1), não uma constante do programa.',
    )


class InstanteMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).',
    )


class DuracaoMs(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(..., description='Duração em milissegundos.')


class Versao(RootModel[constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')]):
    root: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ...,
        description='Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).',
    )


class Correlacao(RootModel[constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9._:/-]{0,63}$')]):
    root: constr(pattern=r'^[A-Za-z0-9][A-Za-z0-9._:/-]{0,63}$') = Field(
        ...,
        description="Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.",
    )


class Instrumento(RootModel[constr(pattern=r'^[A-Z0-9][A-Z0-9._/-]{1,31}$')]):
    root: constr(pattern=r'^[A-Z0-9][A-Z0-9._/-]{1,31}$') = Field(
        ..., description='Símbolo do instrumento, como o venue o escreve.'
    )


class NomeDePlugin(RootModel[constr(pattern=r'^[a-z][a-z0-9_]{1,31}$')]):
    root: constr(pattern=r'^[a-z][a-z0-9_]{1,31}$') = Field(
        ..., description='Nome de setup ou conector: minúsculas, com underscore.'
    )


class Motivo(StrEnum):
    versao_do_contrato_divergente = 'versao_do_contrato_divergente'
    enquadramento_invalido = 'enquadramento_invalido'
    campo_obrigatorio_ausente = 'campo_obrigatorio_ausente'
    valor_nulo_nao_permitido = 'valor_nulo_nao_permitido'
    campo_desconhecido = 'campo_desconhecido'
    campo_em_unidade_de_corretora = 'campo_em_unidade_de_corretora'
    parcial_nao_declarada = 'parcial_nao_declarada'
    formato_invalido = 'formato_invalido'
    tipo_invalido = 'tipo_invalido'
    valor_fora_do_conjunto = 'valor_fora_do_conjunto'
    reversao_com_reduce_only = 'reversao_com_reduce_only'
    reversao_sem_posicao_a_reverter = 'reversao_sem_posicao_a_reverter'
    reducao_parcial_sem_reduce_only = 'reducao_parcial_sem_reduce_only'
    reducao_parcial_sem_posicao_viva = 'reducao_parcial_sem_posicao_viva'
    valor_fora_da_banda = 'valor_fora_da_banda'
    capacidade_nao_declarada = 'capacidade_nao_declarada'
    instrumento_desconhecido_no_manifesto = 'instrumento_desconhecido_no_manifesto'
    minimo_do_instrumento_acima_da_banda = 'minimo_do_instrumento_acima_da_banda'
    prazo_excedido = 'prazo_excedido'
    desfecho_nao_reconhecido = 'desfecho_nao_reconhecido'
    valor_abaixo_do_minimo_do_venue = 'valor_abaixo_do_minimo_do_venue'
    instrumento_deslistado_no_venue = 'instrumento_deslistado_no_venue'
    referencia_ja_enviada_ao_venue = 'referencia_ja_enviada_ao_venue'


class Moeda(RootModel[constr(pattern=r'^[A-Za-z0-9]{1,11}$')]):
    root: constr(pattern=r'^[A-Za-z0-9]{1,11}$') = Field(
        ...,
        description='A MOEDA, como o VENUE a escreve — a banda e a MEDIDA, nao a suposta. ADITIVO na 1.5.0 (tres a cinco letras maiusculas, forcado pelo `USDC` do `feeToken`) e ALARGADO na 1.6.0 ao universo REAL do venue: medido em 29/09/2026 contra `info.meta` + `info.spotMeta` da Hyperliquid (so leitura, sem chave), o venue escreve 1863 moedas/simbolos DISTINTOS (212 perpetuos + 1665 tokens de spot, com 14 nomes partilhados pelos dois), com comprimentos de 1 a 11 — a distribuicao medida por comprimento e 1:11, 2:47, 3:258, 4:489, 5:527, 6:504, 7:17, 8:5, 9:1, 10:2, 11:2. A forma de TRES a CINCO letras maiusculas era FALSA contra esta medicao so pelo comprimento em 589 dos 1863 (as de 1, 2 e de 6 a 11 letras); e, alem do comprimento, 72 dos medidos trazem DIGITO (`TEST1`, `AU0`, `2Z`, `0G`) e 15 trazem MINUSCULA (`kPEPE`, `TestPascal1`, `o1528`). (O numero `1400` que esteve aqui contava tambem os 1329 nomes de PARES de spot — `@1`, `PURR/USDC` — que nao sao moedas; corrigido em 29/09/2026 com a medicao repetida.) Alarga-se ao medido e NAO mais: a banda passa a 1..11 caracteres alfanumericos, maiusculas OU minusculas. Fica dito, porque nao se esconde: dos 1863 medidos, 1862 cabem nesta forma e UM nao — `JPL `, que traz um ESPACO no fim. Nao se alargou a banda para o acomodar: um simbolo com espaco e lixo, e e a prova negativa que o continua a RECUSAR (`formato_invalido`), ao lado do hifen e das 12+ letras. Medicao crua em `specs/004-conector-hyperliquid/relatorios/emenda-1.6.0.txt`.',
    )


class MarcaDePosse(RootModel[conint(ge=0, le=2147483647)]):
    root: conint(ge=0, le=2147483647) = Field(
        ...,
        description='Marca de posse que a MESA compoe (RN-B10): inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment. O `cloid` NAO cabe aqui (0x + 32 hexadecimais, 128 bits) — e o caso `marca/em-hexadecimal-do-cloid` prova-o de proposito. A marca que o VENUE PUBLICA no historico tem a sua propria forma, em `marca_de_posse_do_venue`.',
    )


class MarcaDePosseDoVenue(
    RootModel[conint(ge=0, le=2147483647) | constr(pattern=r'^0x[0-9a-f]{32}$')]
):
    root: conint(ge=0, le=2147483647) | constr(pattern=r'^0x[0-9a-f]{32}$') = Field(
        ...,
        description='A marca de posse que o VENUE PUBLICA (no historico, por execucao), na forma que o MANIFESTO dele declara (`manifesto.marca_de_posse`). ADITIVO na 1.5.0, e obrigado por MEDICAO: a Hyperliquid declara `marca_de_posse: "cloid"` no manifesto e guarda a marca como `0x` + 32 hexadecimais minusculos — que o inteiro de 31 bits da mesa NAO consegue representar (a derivacao do `cloid` e um hash da referencia de cliente, e o inteiro nao esta la dentro). Duas formas, e SO duas: (1) o inteiro de 31 bits (a forma do contrato que ja existia — `marca_de_posse`); (2) o `cloid` pela forma EXACTA. As duas sao disjuntas pelo tipo e nenhuma afrouxa a outra: um inteiro tem de caber nos 31 bits (2147483648 RECUSA, `valor_fora_da_banda`) e um texto tem de ser um `cloid` bem formado (\'nao-e-marca\' RECUSA, `formato_invalido`). Um TERCEIRO tipo de marca nao entra por tolerancia.',
    )


class Lado(StrEnum):
    buy = 'buy'
    sell = 'sell'
    hold = 'hold'
    caixa = 'caixa'
