/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A mensagem central do contrato, em unidades NEUTRAS (RN-B0). Nenhum campo em unidade de corretora: quantidade, lote, preco absoluto, pontos, tick e contrato NAO existem aqui — a resolucao e do conector. A politica de parcial e obrigatoria (RN-B6) e a marca de posse viaja sempre (RN-B10).
 */
export interface BoletaUniversal {
  /**
   * Símbolo do instrumento, como o venue o escreve.
   */
  instrumento: string;
  /**
   * Os EXACTAMENTE quatro valores que a mesa aceita (RN-T4). Qualquer outro é inválido, e um pedido inválido é registado como inválido — nunca corrigido.
   */
  lado: "buy" | "sell" | "hold" | "caixa";
  /**
   * Tipo NEUTRO de ordem. Se o manifesto nao declarar esta capacidade, a boleta e recusada — nao adaptada.
   */
  tipo: "mercado" | "limite" | "stop" | "stop_limite" | "mercado_por_faixa";
  /**
   * Percentagem do SALDO. E um valor do dono (RN-A1), nao uma constante do programa.
   */
  saldo_pct: string;
  /**
   * Multiplo de alavancagem pedido.
   */
  alavancagem: string;
  /**
   * Distancia de stop em percentagem de MOVIMENTO (nao em pontos). Ausente = este setup nao usa stop (RN-S3).
   */
  stop_pct?: string;
  /**
   * Distancia de lucro em percentagem de MOVIMENTO. Ausente = sem alvo declarado.
   */
  tp_pct?: string;
  /**
   * Obrigatoria (RN-B6): o que fazer se so parte da quantidade couber. Escolha do setup, nunca do conector.
   */
  parcial: "tudo_ou_nada" | "o_que_der";
  /**
   * Desvio maximo de preco aceite, em percentagem de movimento.
   */
  desvio_maximo: string;
  /**
   * Quanto tempo a parte passiva da ordem espera antes de o destino do resto decidir.
   */
  prazo_da_passiva_ms: number;
  /**
   * O que fazer com o que ficou por executar quando o prazo da passiva acaba.
   */
  destino_do_resto: "agressivo" | "cancelar";
  /**
   * So reduz posicao. Se o venue nao tiver reduce-only nativo, e o conector que o garante — e tem de o declarar.
   */
  reduce_only: boolean;
  /**
   * Idempotencia: reenviar com a MESMA referencia nao pode criar segunda ordem (RN-C4).
   */
  referencia_do_cliente: string;
  /**
   * Marca de posse: inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment.
   */
  marca_de_posse: number;
}
