/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Um dos CINCO verbos (RN-V1), com autor e correlacao. A forma e a que o recorte 002 ja validava por dentro (R1): este tipo re-aloja-a, nao a redesenha. Campo a mais e RECUSA - aceitar um campo a mais seria a porta dos verbos a alargar-se sozinha, e por aqui a mesa seria comandada em nome de uma estrategia.
 */
export type ComandoDoVigia = {
  /**
   * Os CINCO verbos do vigia (RN-V1). Um sexto nao entra por omissao nem por extensao - e por isso a decisao do encerramento NAO e um verbo, e sim resposta a uma pergunta.
   */
  verbo: "start" | "pause" | "stop" | "reset" | "nova_sessao";
  /**
   * Quem mandou. Um verbo sem autor nao se pode auditar (RN-V4).
   */
  autor: string;
  /**
   * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
   */
  pedido_id: string;
  /**
   * So no `nova_sessao`: a razao de abrir sessao nova e do dono e fica registrada (RN-V10).
   */
  motivo?: string;
};
