/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Nao e um verbo: os verbos do vigia sao CINCO (RN-V1) e a propria recusa `verbo_desconhecido` diz que um sexto nao entra por omissao nem por extensao. A decisao e a RESPOSTA a uma pergunta, e viaja identificada pela pergunta - sem `pedido_id` nao se sabe a que resumo ela responde.
 */
export interface ADecisaoDoDonoSobreOEncerramento {
  /**
   * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
   */
  pedido_id: string;
  /**
   * As duas respostas possiveis a pergunta do encerramento (RN-V7).
   */
  resposta: "fechar_a_mercado" | "manter";
}
