/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O que aconteceu, nos QUATRO valores normalizados (RN-C2). 'desconhecido' e estado de primeira classe: nunca vira sucesso nem falha (RN-T7.1). A recusa traz SEMPRE motivo — recusa sem motivo e recusada pelo proprio contrato.
 */
export type DesfechoDaOrdem = {
  [k: string]: unknown;
} & {
  /**
   * Aceite, parcial, desconhecido ou recusado. Um valor fora destes quatro nao existe no contrato.
   */
  classificacao: "aceite" | "parcial" | "desconhecido" | "recusado";
  /**
   * Obrigatorio quando a classificacao e recusado. Identificador do vocabulario, nunca texto livre.
   */
  motivo?:
    | "versao_do_contrato_divergente"
    | "enquadramento_invalido"
    | "campo_obrigatorio_ausente"
    | "valor_nulo_nao_permitido"
    | "campo_desconhecido"
    | "campo_em_unidade_de_corretora"
    | "parcial_nao_declarada"
    | "formato_invalido"
    | "tipo_invalido"
    | "valor_fora_do_conjunto"
    | "reversao_com_reduce_only"
    | "reversao_sem_posicao_a_reverter"
    | "reducao_parcial_sem_reduce_only"
    | "reducao_parcial_sem_posicao_viva"
    | "valor_fora_da_banda"
    | "capacidade_nao_declarada"
    | "instrumento_desconhecido_no_manifesto"
    | "minimo_do_instrumento_acima_da_banda"
    | "prazo_excedido"
    | "desfecho_nao_reconhecido"
    | "valor_abaixo_do_minimo_do_venue"
    | "instrumento_deslistado_no_venue"
    | "referencia_ja_enviada_ao_venue";
  resolucao?: ResolucaoDoConector;
  /**
   * A resposta BRUTA do venue. O contrato nao a interpreta — o registo guarda-a como chegou, para que nada dependa de interpretacao (FR-021).
   */
  resposta_do_venue: {
    [k: string]: unknown;
  };
};

/**
 * A resolucao faz parte do desfecho (RN-C10) SEMPRE que existiu uma: nao se resolve o que nunca se chegou a resolver. Recusa antes de resolver (capacidade nao declarada, por exemplo) traz motivo e nao traz resolucao.
 */
export interface ResolucaoDoConector {
  /**
   * Na unidade do instrumento, como o manifesto a declara. Nunca arredondada em silencio.
   */
  quantidade: string;
  /**
   * Valor da posicao. E contra o teto do manifesto que se confere.
   */
  nocional: string;
  /**
   * Margem que fica presa. E o que o mandato soma (RN-M5).
   */
  margem_empenhada: string;
  /**
   * A que o venue realmente aplica — pode nao ser a pedida, e entao a resolucao mostra a diferenca.
   */
  alavancagem_efectiva: string;
  /**
   * Preco a que a posicao seria liquidada (RN-M4.13). Zero e valor LEGITIMO: a alavancagem 1 so liquida a preco zero, e o contrato nao pode chamar invalido ao que e verdade.
   */
  preco_de_liquidacao: string;
}
