/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O que atravessa a fronteira: versao, tipo, correlacao e carga. O corpo NAO repete a versao. Todos os objectos sao FECHADOS (D5) e null nao existe (D4).
 */
export type EnvelopeDaMensagem = {
  /**
   * Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).
   */
  contrato: string;
  /**
   * O tipo decide qual e o corpo. Nao ha tipo sem schema.
   */
  tipo:
    | "mercado"
    | "proposta"
    | "boleta"
    | "resolucao"
    | "desfecho"
    | "manifesto"
    | "historico"
    | "comando"
    | "resposta_de_comando"
    | "pergunta_do_encerramento"
    | "decisao_do_encerramento";
  /**
   * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
   */
  id: string;
  carga: {
    [k: string]: unknown;
  };
};
