/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O trilho do dinheiro, como o venue o conta (RN-C11, RN-D6). Taxas e funding em campos PROPRIOS: somar e do venue, nunca da mesa. Nao ha campo de resultado por execucao — recalculado pela mesa seria a mesa a reescrever a conta da corretora.
 */
export interface HistoricoDoVenue {
  /**
   * Símbolo do instrumento, como o venue o escreve.
   */
  instrumento: string;
  moeda: string;
  /**
   * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
   */
  instante_ms: number;
  /**
   * Como o venue o reporta. A mesa mostra, nao reconstroi.
   */
  resultado_realizado: string;
  /**
   * @minItems 1
   */
  execucoes: [
    {
      /**
       * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
       */
      referencia_do_cliente: string;
      /**
       * Marca de posse: inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment.
       */
      marca_de_posse: number;
      /**
       * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
       */
      instante_ms: number;
      lado: "buy" | "sell";
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      quantidade: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      preco: string;
      /**
       * Custo da execucao, como o venue o cobra.
       */
      taxa: string;
      /**
       * Funding da execucao, em campo PROPRIO. Ausente quando o venue nao o reporta por execucao.
       */
      funding?: string;
    },
    ...{
      /**
       * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
       */
      referencia_do_cliente: string;
      /**
       * Marca de posse: inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment.
       */
      marca_de_posse: number;
      /**
       * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
       */
      instante_ms: number;
      lado: "buy" | "sell";
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      quantidade: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      preco: string;
      /**
       * Custo da execucao, como o venue o cobra.
       */
      taxa: string;
      /**
       * Funding da execucao, em campo PROPRIO. Ausente quando o venue nao o reporta por execucao.
       */
      funding?: string;
    }[]
  ];
}
