/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O que o conector DECLARA saber (RN-C1). Sondado no arranque, nunca constante escrita no codigo. Sem declaracao nao ha capacidade: a mesa recusa em vez de tentar (RN-C7).
 */
export interface ManifestoDoConector {
  conector: {
    /**
     * Nome de setup ou conector: minúsculas, com underscore.
     */
    nome: string;
    /**
     * Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).
     */
    versao: string;
  };
  /**
   * Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).
   */
  versao: string;
  /**
   * As unidades declaradas por instrumento. Sem unidade declarada nao ha resolucao possivel.
   *
   * @minItems 1
   */
  instrumentos: [
    {
      /**
       * Símbolo do instrumento, como o venue o escreve.
       */
      simbolo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      minimo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      passo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      tick: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      alavancagem_maxima: string;
      /**
       * Escaloes de valor com maxima proprio. Ausente = vale a maxima unica.
       */
      alavancagem_por_escalao?: {
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        ate: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        maxima: string;
      }[];
    },
    ...{
      /**
       * Símbolo do instrumento, como o venue o escreve.
       */
      simbolo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      minimo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      passo: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      tick: string;
      /**
       * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
       */
      alavancagem_maxima: string;
      /**
       * Escaloes de valor com maxima proprio. Ausente = vale a maxima unica.
       */
      alavancagem_por_escalao?: {
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        ate: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        maxima: string;
      }[];
    }[]
  ];
  sabe_ajustar_alavancagem: boolean;
  /**
   * @minItems 1
   */
  modos_de_margem: ["cruzado" | "isolado", ...("cruzado" | "isolado")[]];
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  teto_de_valor_por_ordem: string;
  modelo_de_posicao: "netting" | "hedging" | "exchange";
  /**
   * @minItems 1
   */
  tipos_de_ordem: [
    "mercado" | "limite" | "stop" | "stop_limite" | "mercado_por_faixa",
    ...("mercado" | "limite" | "stop" | "stop_limite" | "mercado_por_faixa")[]
  ];
  /**
   * @minItems 1
   */
  parcial_suportada: ["tudo_ou_nada" | "o_que_der", ...("tudo_ou_nada" | "o_que_der")[]];
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  desvio_maximo: string;
  /**
   * Se o pedido reduce_only pode ser HONRADO — nativo ou emulado pelo conector. Nao diz o mecanismo: diz a capacidade. Sem esta declaracao, a mesa recusa a boleta em vez de mandar um reduce-only que o venue pode ignorar.
   */
  reduce_only_suportado: boolean;
  /**
   * Se o venue sabe prender stop a uma posicao (o que muda o desfecho de uma parcial).
   */
  stop_anexo: boolean;
  profundidade_de_livro: number;
  funding: boolean;
  relogio_de_fecho_de_barra: "horario" | "meia_noite_utc" | "continuo" | "desconhecido";
  /**
   * Se o venue garante nao duplicar por referencia repetida. Sem isto, a mesa reconcilia ANTES de reenviar (RN-C4).
   */
  idempotencia: boolean;
  /**
   * A forma que este venue aceita. 'nenhuma' e declaracao valida — e a mesa di-lo, em vez de fingir uma marca que nao existe (FR-027).
   */
  marca_de_posse: "cloid" | "clientOrderId" | "magic" | "comment" | "nenhuma";
  marca_liga_ordem_a_posicao: boolean;
  /**
   * Se o venue sabe dizer se o mercado esta aberto (RN-D8). Sem isto, mercado fechado so se detecta pela ausencia de leitura.
   */
  estado_do_mercado: boolean;
}
