/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O objecto de factos que a mesa entrega ao setup E ao humano (RN-D1, RN-D5). So factos. Ausencia e declarada pela ausencia da chave (RN-D4) — nunca por um valor neutro.
 */
export interface ObjectoDeMercado {
  /**
   * Símbolo do instrumento, como o venue o escreve.
   */
  instrumento: string;
  /**
   * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
   */
  tempo_do_venue_ms: number;
  /**
   * Duração em milissegundos.
   */
  idade_do_dado_ms: number;
  /**
   * Mercado fechado e ESTADO, nao erro (RN-D8).
   */
  estado: "aberto" | "fechado";
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  bid?: string;
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  ask?: string;
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  ultimo?: string;
  livro?: {
    /**
     * @minItems 1
     */
    lados: [
      {
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        preco: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        tamanho: string;
      },
      ...{
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        preco: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        tamanho: string;
      }[]
    ];
    /**
     * Profundidade DECLARADA: o setup sabe o que nao ve.
     */
    profundidade: number;
  };
  /**
   * Ausente = sem posicao. A posse le-se do VENUE, pela marca (RN-T16.1).
   */
  posicao?: {
    lado: "buy" | "sell";
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    unidades: string;
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    preco_medio: string;
    /**
     * Marca de posse: inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment.
     */
    marca_de_posse?: number;
  };
  /**
   * Saldo com nao realizado: e sobre isto que o circuit breaker mede (RN-M3).
   */
  equity: string;
  funding?: {
    /**
     * Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.
     */
    taxa: string;
    /**
     * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
     */
    instante_ms: number;
  };
}
