/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O objecto de factos que a mesa entrega ao setup E ao humano (RN-D1, RN-D5). So factos. Ausencia e declarada pela ausencia da chave (RN-D4) — nunca por um valor neutro.
 */
export interface ObjectoDeMercado {
  /**
   * Símbolo do instrumento, como o venue o escreve.
   */
  instrumento: string;
  /**
   * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
   */
  tempo_do_venue_ms: number;
  /**
   * Duração em milissegundos.
   */
  idade_do_dado_ms: number;
  /**
   * Mercado fechado e ESTADO, nao erro (RN-D8).
   */
  estado: "aberto" | "fechado";
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  bid?: string;
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  ask?: string;
  /**
   * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
   */
  ultimo?: string;
  livro?: {
    /**
     * @minItems 1
     */
    lados: [
      {
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        preco: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        tamanho: string;
      },
      ...{
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        preco: string;
        /**
         * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
         */
        tamanho: string;
      }[]
    ];
    /**
     * Profundidade DECLARADA: o setup sabe o que nao ve.
     */
    profundidade: number;
  };
  /**
   * AS ORDENS VIVAS NO VENUE — o que existe na conta e nao e' posicao: o que ficou pendurado, o que ficou por cancelar, o que outro dedo pos. OBRIGATORIA, e LISTA VAZIA NAO E' O MESMO QUE AUSENTE: `[]` diz 'perguntei, e nao ha' nenhuma'; ausente seria 'nao perguntei'. Quem nao conseguiu perguntar NAO PRODUZ leitura (recusa nomeada) — uma lista vazia inventada aqui faria a mesa achar que a conta esta' limpa quando nao esta'.
   */
  ordens_abertas: {
    /**
     * Símbolo do instrumento, como o venue o escreve.
     */
    instrumento: string;
    /**
     * O identificador da ordem NO VENUE (`oid`). E' por ele que a mesa e o humano falam da MESMA ordem.
     */
    ordem: string;
    lado: "buy" | "sell";
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    preco: string;
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    unidades: string;
    /**
     * A marca de posse que o VENUE PUBLICA (no historico, por execucao), na forma que o MANIFESTO dele declara (`manifesto.marca_de_posse`). ADITIVO na 1.5.0, e obrigado por MEDICAO: a Hyperliquid declara `marca_de_posse: "cloid"` no manifesto e guarda a marca como `0x` + 32 hexadecimais minusculos — que o inteiro de 31 bits da mesa NAO consegue representar (a derivacao do `cloid` e um hash da referencia de cliente, e o inteiro nao esta la dentro). Duas formas, e SO duas: (1) o inteiro de 31 bits (a forma do contrato que ja existia — `marca_de_posse`); (2) o `cloid` pela forma EXACTA. As duas sao disjuntas pelo tipo e nenhuma afrouxa a outra: um inteiro tem de caber nos 31 bits (2147483648 RECUSA, `valor_fora_da_banda`) e um texto tem de ser um `cloid` bem formado ('nao-e-marca' RECUSA, `formato_invalido`). Um TERCEIRO tipo de marca nao entra por tolerancia.
     */
    marca_de_posse?: number | string;
  }[];
  /**
   * Ausente = sem posicao. A posse le-se do VENUE, pela marca (RN-T16.1).
   */
  posicao?: {
    lado: "buy" | "sell";
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    unidades: string;
    /**
     * Decimal textual estritamente maior que zero — para percentagens de risco, alavancagem e desvios. Aceita '0.5' (meia percentagem) e recusa '0' e '0.00'.
     */
    preco_medio: string;
    /**
     * Marca de posse que a MESA compoe (RN-B10): inteiro sem sinal de 31 bits, desenhado para a forma MAIS RESTRITA (o POSITION_MAGIC do MT5). Cabe em cloid, clientOrderId, magic e comment. O `cloid` NAO cabe aqui (0x + 32 hexadecimais, 128 bits) — e o caso `marca/em-hexadecimal-do-cloid` prova-o de proposito. A marca que o VENUE PUBLICA no historico tem a sua propria forma, em `marca_de_posse_do_venue`.
     */
    marca_de_posse?: number;
  };
  /**
   * Saldo com nao realizado: e sobre isto que o circuit breaker mede (RN-M3).
   */
  equity: string;
  funding?: {
    /**
     * Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.
     */
    taxa: string;
    /**
     * Instante em milissegundos UTC, do relógio do VENUE — não do processo (RN-D2).
     */
    instante_ms: number;
  };
}
