/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Em `encerrando` a mesa apresenta o resumo e PERGUNTA se fecha a mercado (RN-V7). Os numeros sao DA CORRETORA (RN-V8), nunca estimados por nos - e o resumo existe para que quem escolhe `manter` leia, ANTES, que a posicao fica sem defesa. Por isso o aviso e campo, e nao nota de rodape.
 */
export interface APerguntaDoEncerramento {
  /**
   * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
   */
  pedido_id: string;
  /**
   * @minItems 2
   * @maxItems 2
   *
   * Items: As duas respostas possiveis a pergunta do encerramento (RN-V7).
   */
  opcoes: ["fechar_a_mercado" | "manter", "fechar_a_mercado" | "manter"];
  /**
   * A chave do dono (setup.prazo_de_resposta_ms, RN-A3): quanto a mesa espera antes de voltar a operar com o `stop` pendente (RN-V9.1).
   */
  prazo_de_resposta_ms: number;
  /**
   * Obrigatorio: a pergunta so existe quando ha o que decidir, e um aviso vazio seria um aviso que nao avisa. `null` nao existe neste contrato (D4).
   */
  aviso_de_manter: string;
  /**
   * Cinco numeros do venue. Um venue que nao saiba um deles e materia da bateria de conformidade (RN-C6) e de um DEFEITO declarado - nao de um `null` silencioso.
   */
  numeros: {
    /**
     * Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.
     */
    posicao: string;
    /**
     * Decimal textual sem sinal — para grandezas que não podem ser negativas (idade, profundidade, quantidade, nocional).
     */
    nocional: string;
    /**
     * Decimal textual sem sinal — para grandezas que não podem ser negativas (idade, profundidade, quantidade, nocional).
     */
    margem: string;
    /**
     * Decimal textual sem sinal — para grandezas que não podem ser negativas (idade, profundidade, quantidade, nocional).
     */
    distancia_de_liquidacao: string;
    /**
     * Decimal TEXTUAL. Sem expoente, sem '+', sem '1.'. Um número de vírgula flutuante nunca é um decimal válido — é recusado por tipo, não por arredondamento.
     */
    resultado_nao_realizado: string;
  };
}
