/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A resposta do setup: o lado e, se quiser, o seu relogio. EXACTAMENTE quatro valores (RN-T4). A invalidade NAO e um valor do contrato: 'limpar', vazio ou numero sao recusados aqui, e a mesa trata como hold registando a invalidade.
 */
export interface PropostaDoSetup {
  /**
   * A assinatura que entra no registo (RN-S7).
   */
  setup: {
    /**
     * Nome de setup ou conector: minúsculas, com underscore.
     */
    nome: string;
    /**
     * Versão de contrato, conferida por IGUALDADE EXACTA antes de qualquer envio (D7).
     */
    versao: string;
  };
  /**
   * Os EXACTAMENTE quatro valores que a mesa aceita (RN-T4). Qualquer outro é inválido, e um pedido inválido é registado como inválido — nunca corrigido.
   */
  lado: "buy" | "sell" | "hold" | "caixa";
  /**
   * O setup pode adiantar o prazo do seu template. Ausente, vale o prazo do template (RN-S2, RN-S3).
   */
  relogio?: {
    /**
     * Duração em milissegundos.
     */
    proxima_consulta_ms: number;
  };
}
