/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * O que o conector VAI enviar, devolvido ANTES de executar (RN-C10). Com o desfecho, e a unica mensagem onde aparecem unidades de corretora. Nao ha campo de resto nem de arredondamento: se o minimo do instrumento exigir mais do que a banda autorizada, NAO ha resolucao — ha desfecho recusado com motivo (RN-C9).
 */
export interface ResolucaoDoConector {
  /**
   * Na unidade do instrumento, como o manifesto a declara. Nunca arredondada em silencio.
   */
  quantidade: string;
  /**
   * Valor da posicao. E contra o teto do manifesto que se confere.
   */
  nocional: string;
  /**
   * Margem que fica presa. E o que o mandato soma (RN-M5).
   */
  margem_empenhada: string;
  /**
   * A que o venue realmente aplica — pode nao ser a pedida, e entao a resolucao mostra a diferenca.
   */
  alavancagem_efectiva: string;
  /**
   * Preco a que a posicao seria liquidada (RN-M4.13). Zero e valor LEGITIMO: a alavancagem 1 so liquida a preco zero, e o contrato nao pode chamar invalido ao que e verdade.
   */
  preco_de_liquidacao: string;
}
