/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Recusa NAO e erro de protocolo: e resposta. Quando recusado vem `motivo`; quando aceito vem `efeito` - os dois de conjuntos fechados declarados no vocabulario. A transicao traz estado anterior e posterior, e o instante e do relogio da MESA (RN-M4.9: quem recebe e que carimba).
 */
export type RespostaDaMesaAoComando = {
  [k: string]: unknown;
} & {
  /**
   * Identificador de correlacao do ciclo (RN-T3). E OPACO: compara-se por igualdade, nunca se interpreta. Admite '/' porque a forma natural de correlacionar uma linha com o seu ciclo e 'ciclo/linha' — proibir um caracter inofensivo so cria atrito.
   */
  pedido_id: string;
  aceito: boolean;
  /**
   * Motivo de RECUSA da mesa em resposta a um comando - espelho de vocabulario.json (a fonte e la). Sao 15 dos 42 motivos da mesa: os que o interpretador de comando produz. Os outros 22 nascem dentro de um ciclo e ficam onde nascem (research R7).
   */
  motivo?:
    | "mesa_ja_em_operacao"
    | "mesa_parada_nada_a_pausar"
    | "mesa_ja_pausada"
    | "mesa_ja_parada"
    | "mesa_em_encerramento"
    | "pedido_repetido"
    | "sessao_inibida"
    | "porta_do_arranque_falhou"
    | "liquidacao_em_curso"
    | "sessao_nova_com_posicao_viva"
    | "mesa_precisa_parar_para_sessao_nova"
    | "verbo_desconhecido"
    | "comando_com_campo_a_mais"
    | "comando_incompleto"
    | "comando_com_tipo_invalido"
    | "versao_do_contrato_divergente"
    | "posicao_desconhecida";
  /**
   * So quando ha mais para dizer do que a transicao. Espelho de vocabulario.json.
   */
  efeito?:
    | "sessao_nova_gravada"
    | "reset_nao_toca_em_nada"
    | "resumo_do_encerramento_apresentado"
    | "stop_pendente_por_prazo"
    | "parada_com_posicao_viva";
  transicao: {
    /**
     * O eixo da mesa (docs/maquina-de-estados.md): so estes quatro. A condicao do instrumento e outra coisa e nao entra aqui.
     */
    de: "parada" | "em_operacao" | "pausada" | "encerrando";
    /**
     * O eixo da mesa (docs/maquina-de-estados.md): so estes quatro. A condicao do instrumento e outra coisa e nao entra aqui.
     */
    para: "parada" | "em_operacao" | "pausada" | "encerrando";
  };
  /**
   * Instante em milissegundos, do relogio da MESA - nao do venue (RN-M4.9: quem recebe e que carimba; instante de fora nao se usa, senao quem chama escolhe o lugar na fila).
   */
  instante_ms: number;
};
